package main

import (
	"bufio"
	"fmt"
	"os"
	"strconv"
	"strings"
	"text/template"
)

type Spec struct {
	Common    map[string]int32
	Auth      map[string]int32
	Registry  map[string]int32
	Dbproxy   map[string]int32
	Biz       map[string]int32
	Realtime  map[string]int32
	Gateway   map[string]int32
}

func main() {
	if len(os.Args) != 4 {
		fmt.Fprintf(os.Stderr, "usage: gen-errors <errors.toml> <go_out> <cpp_out>\n")
		os.Exit(1)
	}

	spec, err := parseToml(os.Args[1])
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse toml failed: %v\n", err)
		os.Exit(1)
	}

	entries := flatten(spec)

	if err := writeGo(entries, os.Args[2]); err != nil {
		fmt.Fprintf(os.Stderr, "write go failed: %v\n", err)
		os.Exit(1)
	}
	if err := writeCpp(entries, os.Args[3]); err != nil {
		fmt.Fprintf(os.Stderr, "write cpp failed: %v\n", err)
		os.Exit(1)
	}
}

type Entry struct {
	Name  string
	Code  int32
	Group string
}

func parseToml(path string) (*Spec, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	spec := &Spec{
		Common:   make(map[string]int32),
		Auth:     make(map[string]int32),
		Registry: make(map[string]int32),
		Dbproxy:  make(map[string]int32),
		Biz:      make(map[string]int32),
		Realtime: make(map[string]int32),
		Gateway:  make(map[string]int32),
	}

	var curMap *map[string]int32
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if strings.HasPrefix(line, "[") && strings.HasSuffix(line, "]") {
			section := line[1 : len(line)-1]
			switch section {
			case "common":
				curMap = &spec.Common
			case "auth":
				curMap = &spec.Auth
			case "registry":
				curMap = &spec.Registry
			case "dbproxy":
				curMap = &spec.Dbproxy
			case "biz":
				curMap = &spec.Biz
			case "realtime":
				curMap = &spec.Realtime
			case "gateway":
				curMap = &spec.Gateway
			default:
				curMap = nil
			}
			continue
		}
		if curMap == nil {
			continue
		}
		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}
		key := strings.TrimSpace(parts[0])
		valStr := strings.TrimSpace(parts[1])
		v, err := strconv.ParseInt(valStr, 10, 32)
		if err != nil {
			return nil, fmt.Errorf("invalid value for %s: %s", key, valStr)
		}
		(*curMap)[key] = int32(v)
	}
	return spec, scanner.Err()
}

func flatten(spec *Spec) []Entry {
	groups := []struct {
		name string
		m    map[string]int32
	}{
		{"Common", spec.Common},
		{"Auth", spec.Auth},
		{"Registry", spec.Registry},
		{"Dbproxy", spec.Dbproxy},
		{"Biz", spec.Biz},
		{"Realtime", spec.Realtime},
		{"Gateway", spec.Gateway},
	}

	var out []Entry
	for _, g := range groups {
		for k, v := range g.m {
			out = append(out, Entry{Name: k, Code: v, Group: g.name})
		}
	}
	return out
}

func writeGo(entries []Entry, path string) error {
	tpl := `// Code generated by tools/gen-errors. DO NOT EDIT.

package errors

const (
{{- range . }}
	{{ .Name }} int32 = {{ .Code }} // {{ .Group }}
{{- end }}
)

var codeToName = map[int32]string{
{{- range . }}
	{{ .Code }}: "{{ .Name }}",
{{- end }}
}

// CodeName returns the constant name for a given error code.
func CodeName(code int32) string {
	if name, ok := codeToName[code]; ok {
		return name
	}
	return "UNKNOWN_ERROR"
}
`
	t := template.Must(template.New("go").Parse(tpl))
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	return t.Execute(f, entries)
}

func writeCpp(entries []Entry, path string) error {
	tpl := `// Code generated by tools/gen-errors. DO NOT EDIT.
#pragma once

#include <cstdint>
#include <string>
#include <unordered_map>

namespace gs {
namespace errors {

{{- range . }}
inline constexpr int32_t {{ .Name }} = {{ .Code }}; // {{ .Group }}
{{- end }}

inline const std::unordered_map<int32_t, std::string> kCodeNameMap = {
{{- range . }}
    { {{ .Name }}, "{{ .Name }}" },
{{- end }}
};

inline std::string CodeName(int32_t code) {
    auto it = kCodeNameMap.find(code);
    return it != kCodeNameMap.end() ? it->second : "UNKNOWN_ERROR";
}

} // namespace errors
} // namespace gs
`
	t := template.Must(template.New("cpp").Parse(tpl))
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	return t.Execute(f, entries)
}
