version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: gmaker-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "gmaker"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - gmaker-net

volumes:
  mysql-data:

networks:
  gmaker-net:
    driver: bridge
