port 6376
cluster-enabled yes
cluster-config-file nodes-6376.conf
cluster-node-timeout 5000
appendonly yes
appenddirname appendonlydir
bind 0.0.0.0
protected-mode no
daemonize no
pidfile /var/run/redis_6376.pid
dir /data
loglevel notice
